# https://www.youtube.com/watch?v=vm3YfOHf_Cc

services:
  # MongoDB Service
  metro_mongo_db:
    container_name: metro_db_container
    image: mongo:latest
    restart: always
    ports:
      - 2717:27017
    volumes:
      - metro_db_volume:/data/db

  # Node API Service
  metro_api:
    build: .
    ports:
      - 4000:4000 # localPort:containerPort
    volumes:
      - .:/app
    environment:
      PORT: 3000
      MONGODB_URI_LOCAL: mongodb://metro_mongo_db:27017/metrolistings
    depends_on:
      - metro_mongo_db

# Volume for mongodb
volumes:
  metro_db_volume: {}
